FROM python:3.13
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /usr/src/app
COPY requirements.txt  .
RUN uv pip install --system -r requirements.txt 
COPY . .
CMD ["python", "main.py"]

